name: Blog

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Install Dependencies
        run: |
          echo "开始安装 hexo-cli"
          npm install -g hexo-cli
          npm install
      - name: Build
        run: |
          npm run build
          echo $(ls -l)
          cat index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./public
          publish_branch: blog
