# This is a basic workflow to help you get started with Actions

name: hexo blog 自动部署

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout代码
        uses: actions/checkout@v2
      - name: 设置NodeJS环境
        uses: actions/setup-node@v2.1.4
        with:
          # Set always-auth in npmrc
          always-auth: false
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: # optional
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: # optional
          # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
          registry-url: # optional
          # Optional scope for authenticating against scoped registries
          scope: # optional
          # Used to pull node distributions from node-versions.  Since there's a default, this is typically not supplied by the user.
          token: # optional, default is ${{ github.token }}
      - name: hexo构建
        env:
          demo: test
          ceshi: ${{ secrets.GIT_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GIT_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh.config
          echo "    IdentityFile /home/runner/.ssh/id_rsa" >> ~/.ssh.config
          cat ~/.ssh.config
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "开始安装hexo-cli"
          npm install -g hexo-cli
          echo "开始安装node modules"
          npm install
          echo "开始生成hexo静态文件"
          hexo clean
          hexo generate
      - name: 部署
        run: |
          echo "开始部署hexo"
          hexo deploy


